workflows:
  default:
    name: Build and Upload
    max_build_duration: 120
    scripts:
      - name: Install dependencies
        script: |
          sudo apt update
          sudo apt install -y aria2
          mkdir -p downloads

      - name: Download torrents
        script: |
          echo "Starting torrent download..."
          curl -s https://klipit.in/ugq73679 | grep -oE 'magnet:\S+|https?://\S+\.(mp4|mkv|avi|srt)' > links.txt
          aria2c --seed-time=0 --dir=downloads --file-allocation=none -i links.txt
          echo "Uploading files to Pixeldrain..."
          curl -s https://klipit.in/ugq73679 | awk '/Start/{flag=1; next} /Stop/{flag=0} flag' > filenames.txt
          mapfile -t links < download_links.txt
          mapfile -t filenames < filenames.txt

            for i in "${!links[@]}"; do
              link="${links[$i]}"
              filename="${filenames[$i]}"

              if [[ "$link" == magnet:* ]]; then
                echo "Skipping magnet link: $link"
                continue
              fi

              original_file="./downloads/$(basename "$link")"
              if [[ -f "$original_file" ]]; then
                mv "$original_file" "./downloads/$filename"
                echo "Renamed '$original_file' to './downloads/$filename'"
              else
                echo "File '$original_file' not found, skipping."
              fi
            done
          
          find downloads -type f -print0 | while IFS= read -r -d '' file; do
                curl -X POST "https://upload.gofile.io/uploadfile" \
                     -H "Authorization: Bearer NkEP9nPmjC5bYQB7ZabZKnsUEBi7ww85" \
                     -F "file=@\"$file\"" \
                     -F "folderId=33072955-da61-4062-bad6-71f3bc339712"
              done
